name: codasign
description: CodaSign - A sign document project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  auto_route: ^11.1.0
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  drift: ^2.20.1
  drift_flutter: ^0.2.2
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hsvcolor_picker: ^1.5.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  signature: ^5.5.0
  syncfusion_flutter_pdf: ^32.2.5
  syncfusion_flutter_pdfviewer: ^32.2.5
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^10.4.0
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
