name: codasign
description: CodaSign - A sign document project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  auto_route: ^9.2.2
  drift: ^2.20.1
  drift_flutter: ^0.2.2
  dio: ^5.7.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  signature: ^5.5.0
  syncfusion_flutter_pdfviewer: ^28.1.33
  pdf: ^3.11.1
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  drift_dev: ^2.20.2

flutter:
  generate: true
  uses-material-design: true
